### ISSUE TITLE
Add deprecation for `hsts`

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon-linter#21]
Routes could be configured to return the HSTS header by using the `hsts` field. The format was:

```
environments:
  main:
    routes:
      - nginx:
        - "www.example.com":
            hsts: max-age=31536000
```

HSTS is still supported, but the field names have changed, so existing `hsts` fields should throw a deprecation.
