### ISSUE TITLE
Add deprecation for insecure routes option, `None`

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/lagoon-linter#22]
Routes have an `insecure` field that can be set to `Allow`, `Redirect`, or `None`. The `None` option used to block any HTTP connections under openshfit, but in kubernetes we've configured it to be the same as `Redirect`. We can throw deprecations for `None` because it no longer works the way it was documented.

It could be set for autogenerated routes:
```
routes:
  autogenerate:
    insecure: None
```

and/or for manual routes:
```
environments:
  main:
    routes:
      - nginx:
        - "www.example.com":
            insecure: None
```
