### ISSUE TITLE
Incorrectly defined, but valid "lagoon" yaml fails to lint

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon-linter#8]
Because Lagoons `.lagoon.yml` is pretty terrible. There are some cases where the defined yaml passes the Lagoon build phase, but the linter can't decode properly.

For example, the following will deploy a lagoon environment correctly, even though `cronjobs:` are defined as an environment.
The linter fails to unmarshal this and errors preventing a build
```
environments:
  cronjobs:
    - name: a cronjob defined as environment
      schedule: "* * * * *"
      command: echo "broken definition"
      service: cli
  main:
    routes:
    - nginx:
      - example.com
      - "www.example.com":
          tls-acme: 'true'
          insecure: Redirect
          hsts: max-age=31536000
```
